// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIM_DESENVOLTECH.Models;

#nullable disable

namespace PIM_DESENVOLTECH.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20231116222558_Inicial-Models3")]
    partial class InicialModels3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PIM_DESENVOLTECH.Models.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdFuncionario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"));

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataAdmissao");

                    b.Property<DateTime>("DataDemissao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataDemissao");

                    b.Property<bool>("FuncionarioAtivo")
                        .HasColumnType("bit")
                        .HasColumnName("FuncionarioAtivo");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int")
                        .HasColumnName("PK_IdPessoa");

                    b.Property<string>("NomeCargo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeCargo");

                    b.Property<string>("Salario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Salario");

                    b.HasKey("IdFuncionario");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("PIM_DESENVOLTECH.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdm")
                        .HasColumnType("bit")
                        .HasColumnName("IsAdm");

                    b.Property<string>("NomeLogin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeLogin");

                    b.Property<string>("SenhaLogin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SenhaLogin");

                    b.HasKey("Id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("PIM_DESENVOLTECH.Models.Logradouro", b =>
                {
                    b.Property<int>("IdLogradouro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdLogradouro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogradouro"));

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cidade");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Complemento");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Estado");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("PK_IdFuncionario");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int")
                        .HasColumnName("PK_IdPessoa");

                    b.Property<string>("NumeroRua")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NumeroRua");

                    b.HasKey("IdLogradouro");

                    b.ToTable("Logradouro");
                });

            modelBuilder.Entity("PIM_DESENVOLTECH.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPessoa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoa"));

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CPF");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("PK_IdFuncionario");

                    b.Property<int>("IdLogradouro")
                        .HasColumnType("int")
                        .HasColumnName("IdLogradouro");

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("Idade");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("Nascimento");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeCompleto");

                    b.Property<string>("RG")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RG");

                    b.HasKey("IdPessoa");

                    b.ToTable("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
